// <auto-generated />
namespace PoolMonitoringWebRole.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addsensordata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsensordata));
        
        string IMigrationMetadata.Id
        {
            get { return "201506141230469_add-sensor-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
